# Run all benchmarks when a comment containing "test performance please"
# comment is posted on a PR.

name: Benchmarks Comment Handler

on:
  issue_comment:
    types: [created]

jobs:
  run_benchmarks:
    name: Run Benchmarks
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'test performance please')
    runs-on: ["self-hosted", "benchmarks"]

    steps:
      - name: Find parent main commit
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.exportVariable('BASE_SHA', data.base.sha);
            core.exportVariable('HEAD_SHA', data.head.sha);
            core.exportVariable('HEAD_REPO', data.head.repo.full_name);

      - name: Benchmark base commit
        uses: ./.github/workflows/bench.yml
        with:
          commit: ${{ env.BASE_SHA }}
          repo: "scala/scala3"
          run: 0
          is_last_run: false

      - name: Benchmark last PR commit
        uses: ./.github/workflows/bench.yml
        with:
          commit: ${{ env.HEAD_SHA }}
          repo: ${{ env.HEAD_REPO }}
          run: 0
          is_last_run: false
