name: Update Dependency Graph
on: [workflow_dispatch] # Disabled on fork

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v3
