name: LARA Release to Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NIGHTLYBUILD: "yes"
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_TOKEN }}
      PGP_PASSPHRASE: ${{ secrets.SONATYPE_PGP_PASSPHRASE }}
      SBT_PGP_USE_GPG: "true"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.SONATYPE_PGP_KEY }}
          passphrase: ${{ secrets.SONATYPE_PGP_PASSPHRASE }}
      - name: Get version string
        run: |
          ver=$(./project/scripts/sbt "print scala3-compiler-bootstrapped/version" | tail -n1)
          echo "Publishing version: $ver"
      - name: Sign and stage artifacts locally
        run: sbt scala3-bootstrapped/publishSigned
      - name: Upload and release to Maven Central
        run: sbt sonaRelease
